development:
  bucket: austinprobono-dev
  access_key_id: 'XXX'
  secret_access_key: 'XXX'
test:
  bucket: austinprobono-test
  access_key_id: 'XXX'
  secret_access_key: 'XXX'
production:
  bucket: austinprobono
  access_key_id: 'XXX'
  secret_access_key: 'XXX'

